src = Split('''
opengl/glfuncs.d
opengl/gltypes.d
opengl/glfw.d
''')

src += Split('''
src/main.d
''')

env = Environment()
env['LINKFLAGS'] = '-m64 -lpthread -lphobos2 -lGL -lglfw -lrt'
env.Program("glfwtest", src, TARGET_ARCH='x86_64', DFLAGS = Split("-unittest -gc -g -m64"))
