src = Split('''
opengl/glfuncs.d
opengl/gltypes.d
opengl/glfw.d
''')

src += Split('''
src/main.d
''')

env = Environment()
env.Program("dngine", src, DFLAGS = Split("-unittest -gc -g -Igl3n/import"), LIBPATH="gl3n/lib/", LIBS=["pthread", "rt", "phobos2", "GL", "glfw", "gl3n-dmd"])
